SET local check_function_bodies = OFF;

CREATE TABLE "public"."community_reports" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "title" text NOT NULL,
    "description" text NOT NULL,
    "image_url" text NOT NULL,
    "location" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "category" text NOT NULL,
    CONSTRAINT "community_reports_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."community_reports" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."profiles" (
    "id" uuid NOT NULL,
    "role" text,
    CONSTRAINT "profiles_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."reports" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" uuid NOT NULL,
    "title" text NOT NULL,
    "description" text NOT NULL,
    "image_url" text NOT NULL,
    "location" text NOT NULL,
    "community_report_id" bigint,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "category" text NOT NULL,
    CONSTRAINT "reports_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."reports" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."votes" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" uuid NOT NULL,
    "community_report_id" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "votes_pkey" PRIMARY KEY (id),
    CONSTRAINT "votes_user_id_community_report_id_key" UNIQUE (user_id, community_report_id)
);

ALTER TABLE "public"."votes" ENABLE ROW LEVEL SECURITY;

CREATE TYPE "public"."report_status" AS ENUM (
    'pending',
    'in-progress',
    'resolved'
);

ALTER TABLE "public"."community_reports"
    ADD COLUMN "status" public.report_status NOT NULL DEFAULT 'pending'::public.report_status;

ALTER TABLE "public"."reports"
    ADD COLUMN "status" public.report_status NOT NULL DEFAULT 'pending'::public.report_status;

CREATE TYPE "public"."vote_type" AS ENUM (
    'up',
    'down',
    'neutral'
);

ALTER TABLE "public"."votes"
    ADD COLUMN "vote" public.vote_type NOT NULL;

CREATE OR REPLACE FUNCTION public.rls_auto_enable ()
    RETURNS event_trigger
    LANGUAGE plpgsql
    SECURITY DEFINER
    SET search_path TO 'pg_catalog'
    AS $function$
DECLARE
    cmd record;
BEGIN
    FOR cmd IN
    SELECT
        *
    FROM
        pg_event_trigger_ddl_commands ()
    WHERE
        command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
        AND object_type IN ('table', 'partitioned table')
        LOOP
            IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog', 'information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
                BEGIN
                    EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
                    RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
                EXCEPTION
                    WHEN OTHERS THEN
                        RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
                END;
            ELSE
                RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
            END IF;
    END LOOP;
END;

$function$;

ALTER TABLE "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users (id);

ALTER TABLE "public"."reports"
    ADD CONSTRAINT "reports_community_report_id_fkey" FOREIGN KEY (community_report_id) REFERENCES public.community_reports (id) ON DELETE SET NULL;

ALTER TABLE "public"."reports"
    ADD CONSTRAINT "reports_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users (id);

ALTER TABLE "public"."votes"
    ADD CONSTRAINT "votes_community_report_id_fkey" FOREIGN KEY (community_report_id) REFERENCES public.community_reports (id) ON DELETE CASCADE;

ALTER TABLE "public"."votes"
    ADD CONSTRAINT "votes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users (id);

CREATE POLICY "allow authenticated crud" ON "public"."community_reports"
    FOR ALL TO "authenticated"
    USING (TRUE);

CREATE POLICY "allow authenticated crud" ON "public"."profiles"
    FOR ALL TO "authenticated"
    USING (TRUE);

CREATE POLICY "allow authenticated crud" ON "public"."reports"
    FOR ALL TO "authenticated"
    USING (TRUE);

CREATE POLICY "allow authenticated crud" ON "public"."votes"
    FOR ALL TO PUBLIC
    USING (TRUE);

CREATE POLICY "allow authenticated crud 1i04aub_0" ON "storage"."objects"
    FOR DELETE TO "authenticated"
    USING ((bucket_id = 'report_images'::text));

CREATE POLICY "allow authenticated crud 1i04aub_1" ON "storage"."objects"
    FOR SELECT TO "authenticated"
    USING ((bucket_id = 'report_images'::text));

CREATE POLICY "allow authenticated crud 1i04aub_2" ON "storage"."objects"
    FOR UPDATE TO "authenticated"
    USING ((bucket_id = 'report_images'::text));

CREATE POLICY "allow authenticated crud 1i04aub_3" ON "storage"."objects"
    FOR INSERT TO "authenticated"
    WITH CHECK ((bucket_id = 'report_images'::text));

CREATE EVENT TRIGGER "ensure_rls" ON ddl_command_end
    WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
        EXECUTE FUNCTION "public"."rls_auto_enable" ();

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable" () TO PUBLIC, "anon", "authenticated";

REVOKE ALL ON FUNCTION "public"."rls_auto_enable" () FROM "postgres";

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable" () TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable" () TO "service_role";

REVOKE ALL ON SEQUENCE "public"."community_reports_id_seq"
    FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."community_reports_id_seq"
    TO "anon";

REVOKE ALL ON SEQUENCE "public"."community_reports_id_seq"
    FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."community_reports_id_seq"
    TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."community_reports_id_seq"
    FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."community_reports_id_seq"
    TO "postgres";

REVOKE ALL ON SEQUENCE "public"."community_reports_id_seq"
    FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."community_reports_id_seq"
    TO "service_role";

REVOKE ALL ON SEQUENCE "public"."reports_id_seq"
    FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."reports_id_seq"
    TO "anon";

REVOKE ALL ON SEQUENCE "public"."reports_id_seq"
    FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."reports_id_seq"
    TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."reports_id_seq"
    FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."reports_id_seq"
    TO "postgres";

REVOKE ALL ON SEQUENCE "public"."reports_id_seq"
    FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."reports_id_seq"
    TO "service_role";

REVOKE ALL ON SEQUENCE "public"."votes_id_seq"
    FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."votes_id_seq"
    TO "anon";

REVOKE ALL ON SEQUENCE "public"."votes_id_seq"
    FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."votes_id_seq"
    TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."votes_id_seq"
    FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."votes_id_seq"
    TO "postgres";

REVOKE ALL ON SEQUENCE "public"."votes_id_seq"
    FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."votes_id_seq"
    TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_reports" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."community_reports" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_reports" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."community_reports" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."profiles" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reports" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."reports" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reports" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reports" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."votes" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."votes" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."votes" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."votes" TO "service_role";

