SET local check_function_bodies = off;

CREATE EXTENSION "pg_net" SCHEMA "extensions";

CREATE EXTENSION "postgis" SCHEMA "public";

CREATE EXTENSION "vector" SCHEMA "public";

CREATE TABLE "public"."incident" (
  "id"                  bigint                   GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."community_reports_id_seq") NOT NULL,
  "title"               text,
  "description"         text                     NOT NULL,
  "image_url"           text                     NOT NULL,
  "location"            public.geography         NOT NULL,
  "created_at"          timestamp with time zone NOT NULL DEFAULT now(),
  "category"            text                     NOT NULL,
  "is_community_report" boolean                  NOT NULL DEFAULT false,
  "location_name"       text                     NOT NULL,
  "embedding"           public.vector            NOT NULL,
  CONSTRAINT "community_reports_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."incident"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."profile" (
  "id"   uuid NOT NULL,
  "role" text,
  CONSTRAINT "profiles_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."profile"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."report" (
  "id"            bigint                   GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."reports_id_seq") NOT NULL,
  "user_id"       uuid                     NOT NULL,
  "description"   text                     NOT NULL,
  "image_url"     text                     NOT NULL,
  "location"      public.geography         NOT NULL,
  "incident_id"   bigint                   NOT NULL,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "category"      text                     NOT NULL,
  "location_name" text                     NOT NULL,
  CONSTRAINT "reports_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."report"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."vote" (
  "id"          bigint                   GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."votes_id_seq") NOT NULL,
  "user_id"     uuid                     NOT NULL,
  "incident_id" bigint                   NOT NULL,
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "votes_pkey" PRIMARY KEY (id),
  CONSTRAINT "votes_user_id_community_report_id_key" UNIQUE (user_id, incident_id)
);

ALTER TABLE "public"."vote"
  ENABLE ROW LEVEL SECURITY;

CREATE TYPE "public"."report_status" AS ENUM (
  'pending',
  'in-progress',
  'resolved'
);

ALTER TABLE "public"."incident"
  ADD COLUMN "status" public.report_status NOT NULL DEFAULT 'pending'::public.report_status;

CREATE TYPE "public"."vote_type" AS ENUM (
  'up',
  'down',
  'neutral'
);

ALTER TABLE "public"."vote"
  ADD COLUMN "vote_type" public.vote_type NOT NULL;

CREATE OR REPLACE FUNCTION public.get_nearby_incidents (
  query_lat       double precision,
  query_lng       double precision,
  query_category  text,
  query_embedding public.vector,
  radius_meters   double precision DEFAULT 50,
  match_threshold double precision DEFAULT 0.5,
  exclude_user_id uuid             DEFAULT NULL::uuid
)
  RETURNS TABLE (
    id                  bigint,
    title               text,
    description         text,
    category            text,
    status              text,
    image_url           text,
    is_community_report boolean,
    distance_meters     double precision,
    lat                 double precision,
    lng                 double precision,
    similarity          double precision
  )
  LANGUAGE plpgsql
  AS $function$
begin
  return query
  select
    i.id,
    i.title,
    i.description,
    i.category,
    i.status::text, -- Cast the custom enum to standard text
    i.image_url,
    i.is_community_report,
    
    ST_Distance(
      i.location, 
      ST_SetSRID(ST_MakePoint(query_lng, query_lat), 4326)::geography
    ) as distance_meters,
    ST_Y(i.location::geometry) as lat,
    ST_X(i.location::geometry) as lng,
    1 - (i.embedding <=> query_embedding) as similarity
  from
    incident i
  where
    i.category = query_category
    and ST_DWithin(
      i.location,
      ST_SetSRID(ST_MakePoint(query_lng, query_lat), 4326)::geography,
      radius_meters
    )
    and (1 - (i.embedding <=> query_embedding)) >= match_threshold
  order by
    (i.embedding <=> query_embedding) asc,
    i.location <-> ST_SetSRID(ST_MakePoint(query_lng, query_lat), 4326)::geography asc
  limit 3;
end;
$function$;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
  RETURNS event_trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog'
  AS $function$
DECLARE
    cmd record;
BEGIN
    FOR cmd IN
    SELECT
        *
    FROM
        pg_event_trigger_ddl_commands ()
    WHERE
        command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
        AND object_type IN ('table', 'partitioned table')
        LOOP
            IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog', 'information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
                BEGIN
                    EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
                    RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
                EXCEPTION
                    WHEN OTHERS THEN
                        RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
                END;
            ELSE
                RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
            END IF;
    END LOOP;
END;

$function$;

ALTER TABLE "public"."profile"
  ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id);

ALTER TABLE "public"."report"
  ADD CONSTRAINT "reports_incident_id_fkey" FOREIGN KEY (incident_id) REFERENCES public.incident(id) ON DELETE SET NULL;

ALTER TABLE "public"."report"
  ADD CONSTRAINT "reports_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);

ALTER TABLE "public"."vote"
  ADD CONSTRAINT "votes_community_report_id_fkey" FOREIGN KEY (incident_id) REFERENCES public.incident(id) ON DELETE CASCADE;

ALTER TABLE "public"."vote"
  ADD CONSTRAINT "votes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);

CREATE POLICY "allow authenticated crud" ON "public"."incident"
  FOR ALL
  TO "authenticated"
  USING (true);

CREATE POLICY "allow authenticated crud" ON "public"."profile"
  FOR ALL
  TO "authenticated"
  USING (true);

CREATE POLICY "allow authenticated crud" ON "public"."report"
  FOR ALL
  TO "authenticated"
  USING (true);

CREATE POLICY "allow authenticated crud" ON "public"."vote"
  FOR ALL
  TO PUBLIC
  USING (true);

CREATE POLICY "allow authenticated crud 1i04aub_0" ON "storage"."objects"
  FOR DELETE
  TO PUBLIC
  USING ((bucket_id = 'report_images'::text));

CREATE POLICY "allow authenticated crud 1i04aub_1" ON "storage"."objects"
  FOR SELECT
  TO PUBLIC
  USING ((bucket_id = 'report_images'::text));

CREATE POLICY "allow authenticated crud 1i04aub_2" ON "storage"."objects"
  FOR UPDATE
  TO PUBLIC
  USING ((bucket_id = 'report_images'::text));

CREATE POLICY "allow authenticated crud 1i04aub_3" ON "storage"."objects"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((bucket_id = 'report_images'::text));

CREATE EVENT TRIGGER "ensure_rls"
  ON ddl_command_end
  WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  EXECUTE FUNCTION "public"."rls_auto_enable"();

COMMENT ON EXTENSION "pg_net" IS 'Async HTTP';

COMMENT ON EXTENSION "postgis" IS 'PostGIS geometry and geography spatial types and functions';

COMMENT ON EXTENSION "vector" IS 'vector data type and ivfflat and hnsw access methods';

GRANT EXECUTE
  ON FUNCTION "public"."get_nearby_incidents"(double precision, double precision, text, public.vector, double precision, double precision, uuid)
  TO PUBLIC, "anon", "authenticated";

REVOKE ALL ON FUNCTION "public"."get_nearby_incidents"(double precision, double precision, text, public.vector, double precision, double precision, uuid) FROM "postgres";

GRANT EXECUTE ON FUNCTION "public"."get_nearby_incidents"(double precision, double precision, text, public.vector, double precision, double precision, uuid) TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."get_nearby_incidents"(double precision, double precision, text, public.vector, double precision, double precision, uuid) TO "service_role";

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO PUBLIC, "anon", "authenticated";

REVOKE ALL ON FUNCTION "public"."rls_auto_enable"() FROM "postgres";

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO "postgres";

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO "service_role";

REVOKE ALL ON SEQUENCE "public"."community_reports_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."community_reports_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."community_reports_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."community_reports_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."community_reports_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."community_reports_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."community_reports_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."community_reports_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."reports_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."reports_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."reports_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."reports_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."reports_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."reports_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."reports_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."reports_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."votes_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."votes_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."votes_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."votes_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."votes_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."votes_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."votes_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."votes_id_seq" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."incident" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."incident" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."incident" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."incident" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profile" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."profile" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profile" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profile" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."report" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."report" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."report" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."report" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."vote" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."vote" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."vote" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."vote" TO "service_role";
