SET statement_timeout = 0;

SET lock_timeout = 0;

SET idle_in_transaction_session_timeout = 0;

SET client_encoding = 'UTF8';

SET standard_conforming_strings = ON;

SELECT
    pg_catalog.set_config('search_path', '', FALSE);

SET check_function_bodies = FALSE;

SET xmloption = content;

SET client_min_messages = warning;

SET row_security = OFF;

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE TYPE "public"."report_status" AS ENUM (
    'pending',
    'in-progress',
    'resolved'
);

ALTER TYPE "public"."report_status" OWNER TO "postgres";

CREATE TYPE "public"."vote_type" AS ENUM (
    'up',
    'down',
    'neutral'
);

ALTER TYPE "public"."vote_type" OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."rls_auto_enable" ()
    RETURNS "event_trigger"
    LANGUAGE "plpgsql"
    SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
    cmd record;
BEGIN
    FOR cmd IN
    SELECT
        *
    FROM
        pg_event_trigger_ddl_commands ()
    WHERE
        command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
        AND object_type IN ('table', 'partitioned table')
        LOOP
            IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog', 'information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
                BEGIN
                    EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
                    RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
                EXCEPTION
                    WHEN OTHERS THEN
                        RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
                END;
            ELSE
                RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
            END IF;
    END LOOP;
END;

$$;

ALTER FUNCTION "public"."rls_auto_enable" () OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."incident" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "image_url" "text" NOT NULL,
    "location" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now" () NOT NULL,
    "category" "text" NOT NULL,
    "status" "public"."report_status" DEFAULT 'pending'::"public"."report_status" NOT NULL,
    "is_community_report" boolean DEFAULT FALSE
);

ALTER TABLE "public"."incident" OWNER TO "postgres";

ALTER TABLE "public"."incident"
    ALTER COLUMN "id"
    ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME
        "public"."community_reports_id_seq" START WITH 1 INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1);

CREATE TABLE IF NOT EXISTS "public"."profile" (
    "id" "uuid" NOT NULL,
    "role" "text"
);

ALTER TABLE "public"."profile" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."report" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "description" "text" NOT NULL,
    "image_url" "text" NOT NULL,
    "location" "text" NOT NULL,
    "incident_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now" () NOT NULL,
    "category" "text" NOT NULL,
    "status" "public"."report_status" DEFAULT 'pending'::"public"."report_status" NOT NULL
);

ALTER TABLE "public"."report" OWNER TO "postgres";

ALTER TABLE "public"."report"
    ALTER COLUMN "id"
    ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME
        "public"."reports_id_seq" START WITH 1 INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1);

CREATE TABLE IF NOT EXISTS "public"."vote" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "incident_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now" () NOT NULL,
    "vote" "public"."vote_type" NOT NULL
);

ALTER TABLE "public"."vote" OWNER TO "postgres";

ALTER TABLE "public"."vote"
    ALTER COLUMN "id"
    ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME
        "public"."votes_id_seq" START WITH 1 INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1);

ALTER TABLE ONLY "public"."incident"
    ADD CONSTRAINT "community_reports_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."profile"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."report"
    ADD CONSTRAINT "reports_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."vote"
    ADD CONSTRAINT "votes_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."vote"
    ADD CONSTRAINT "votes_user_id_community_report_id_key" UNIQUE ("user_id", "incident_id");

ALTER TABLE ONLY "public"."profile"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users" ("id");

ALTER TABLE ONLY "public"."report"
    ADD CONSTRAINT "reports_incident_id_fkey" FOREIGN KEY ("incident_id") REFERENCES "public"."incident" ("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."report"
    ADD CONSTRAINT "reports_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users" ("id");

ALTER TABLE ONLY "public"."vote"
    ADD CONSTRAINT "votes_community_report_id_fkey" FOREIGN KEY ("incident_id") REFERENCES "public"."incident" ("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."vote"
    ADD CONSTRAINT "votes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users" ("id");

CREATE POLICY "allow authenticated crud" ON "public"."incident" TO "authenticated"
    USING (TRUE);

CREATE POLICY "allow authenticated crud" ON "public"."profile" TO "authenticated"
    USING (TRUE);

CREATE POLICY "allow authenticated crud" ON "public"."report" TO "authenticated"
    USING (TRUE);

CREATE POLICY "allow authenticated crud" ON "public"."vote"
    USING (TRUE);

ALTER TABLE "public"."incident" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."profile" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."report" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."vote" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "anon";

GRANT USAGE ON SCHEMA "public" TO "authenticated";

GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON FUNCTION "public"."rls_auto_enable" () TO "anon";

GRANT ALL ON FUNCTION "public"."rls_auto_enable" () TO "authenticated";

GRANT ALL ON FUNCTION "public"."rls_auto_enable" () TO "service_role";

GRANT ALL ON TABLE "public"."incident" TO "anon";

GRANT ALL ON TABLE "public"."incident" TO "authenticated";

GRANT ALL ON TABLE "public"."incident" TO "service_role";

GRANT ALL ON SEQUENCE "public"."community_reports_id_seq"
    TO "anon";

GRANT ALL ON SEQUENCE "public"."community_reports_id_seq"
    TO "authenticated";

GRANT ALL ON SEQUENCE "public"."community_reports_id_seq"
    TO "service_role";

GRANT ALL ON TABLE "public"."profile" TO "anon";

GRANT ALL ON TABLE "public"."profile" TO "authenticated";

GRANT ALL ON TABLE "public"."profile" TO "service_role";

GRANT ALL ON TABLE "public"."report" TO "anon";

GRANT ALL ON TABLE "public"."report" TO "authenticated";

GRANT ALL ON TABLE "public"."report" TO "service_role";

GRANT ALL ON SEQUENCE "public"."reports_id_seq"
    TO "anon";

GRANT ALL ON SEQUENCE "public"."reports_id_seq"
    TO "authenticated";

GRANT ALL ON SEQUENCE "public"."reports_id_seq"
    TO "service_role";

GRANT ALL ON TABLE "public"."vote" TO "anon";

GRANT ALL ON TABLE "public"."vote" TO "authenticated";

GRANT ALL ON TABLE "public"."vote" TO "service_role";

GRANT ALL ON SEQUENCE "public"."votes_id_seq"
    TO "anon";

GRANT ALL ON SEQUENCE "public"."votes_id_seq"
    TO "authenticated";

GRANT ALL ON SEQUENCE "public"."votes_id_seq"
    TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";

--
-- Dumped schema changes for auth and storage
--
CREATE POLICY "allow authenticated crud 1i04aub_0" ON "storage"."objects"
    FOR DELETE TO "authenticated"
    USING (("bucket_id" = 'report_images'::"text"));

CREATE POLICY "allow authenticated crud 1i04aub_1" ON "storage"."objects"
    FOR SELECT TO "authenticated"
    USING (("bucket_id" = 'report_images'::"text"));

CREATE POLICY "allow authenticated crud 1i04aub_2" ON "storage"."objects"
    FOR UPDATE TO "authenticated"
    USING (("bucket_id" = 'report_images'::"text"));

CREATE POLICY "allow authenticated crud 1i04aub_3" ON "storage"."objects"
    FOR INSERT TO "authenticated"
    WITH CHECK (("bucket_id" = 'report_images'::"text"));

